project:
  type: website
  output-dir: _site  # Ensure the output is set to the correct folder

website:
  title: "Yimin Ding's Personal Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Analysis"
        href: analysis.qmd
