project:
  type: website

website:
  title: "Yimin Ding's Personal Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Analysis"
        href: analysis.qmd
